<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29029" started-at="2020-09-25T14:00:55 IST" finished-at="2020-09-25T14:01:24 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29029" started-at="2020-09-25T14:00:55 IST" finished-at="2020-09-25T14:01:24 IST">
      <class name="com.mmt.tests.MMTHomepageTests">
        <test-method status="PASS" signature="preSetup()[pri:0, instance:com.mmt.tests.MMTHomepageTests@536aaa8d]" name="preSetup" is-config="true" duration-ms="178" started-at="2020-09-25T14:00:55 IST" finished-at="2020-09-25T14:00:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.mmt.tests.MMTHomepageTests@536aaa8d]" name="setup" is-config="true" duration-ms="15408" started-at="2020-09-25T14:00:55 IST" finished-at="2020-09-25T14:01:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyApplicationLaunch()[pri:0, instance:com.mmt.tests.MMTHomepageTests@536aaa8d]" name="verifyApplicationLaunch" duration-ms="12254" started-at="2020-09-25T14:01:11 IST" finished-at="2020-09-25T14:01:23 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [com.mmt.travel.app.home.ui.SplashActivity] but found [com.mmt.travel.app.hotel.activity.HotelLandingActivity]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [com.mmt.travel.app.home.ui.SplashActivity] but found [com.mmt.travel.app.hotel.activity.HotelLandingActivity]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.mmt.tests.MMTHomepageTests.verifyApplicationLaunch(MMTHomepageTests.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyApplicationLaunch -->
        <test-method status="PASS" signature="postTestActions(org.testng.ITestResult)[pri:0, instance:com.mmt.tests.MMTHomepageTests@536aaa8d]" name="postTestActions" is-config="true" duration-ms="726" started-at="2020-09-25T14:01:23 IST" finished-at="2020-09-25T14:01:24 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyApplicationLaunch status=FAILURE method=MMTHomepageTests.verifyApplicationLaunch()[pri:0, instance:com.mmt.tests.MMTHomepageTests@536aaa8d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postTestActions -->
        <test-method status="PASS" signature="ceanUp()[pri:0, instance:com.mmt.tests.MMTHomepageTests@536aaa8d]" name="ceanUp" is-config="true" duration-ms="603" started-at="2020-09-25T14:01:24 IST" finished-at="2020-09-25T14:01:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ceanUp -->
        <test-method status="PASS" signature="postCleanup()[pri:0, instance:com.mmt.tests.MMTHomepageTests@536aaa8d]" name="postCleanup" is-config="true" duration-ms="466" started-at="2020-09-25T14:01:24 IST" finished-at="2020-09-25T14:01:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCleanup -->
      </class> <!-- com.mmt.tests.MMTHomepageTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
